### ISSUE TITLE
Fails to build on !Linux since 22845a97

### ISSUE THREAD

**Issue by evgeni** [draios/sysdig#455]
Heya,

in 22845a97 you introduced a new file: driver/driver_config.h.in which generates driver/driver_config.h. The later is then used by the userspace code to get a few variables.

However, driver/driver_config.h is only built, when the driver directory is built. Which is not the case on non-Linux systems (I tried on Debian/kFreeBSD and Debian/Hurd).

The build then fails with the following error

    userspace/libscap/scap.c:34:40: fatal error: ../../driver/driver_config.h: No such file or directory

Putting `add_subdirectory(driver)` outside of `if(CMAKE_SYSTEM_NAME MATCHES "Linux")` worked for my testbuilds (they have `BUILD_DRIVER=OFF` anyways) but I don't really like that solution yet.

**Comment by evgeni** [comment]
cc @hlieberman

**Comment by gianlucaborello** [comment]
I think the right solution might be changing this ifdef https://github.com/draios/sysdig/blob/master/userspace/sysdig/sysdig.h#L22 and this other one https://github.com/draios/sysdig/blob/master/userspace/libscap/scap.c#L33 from "_WIN32" to "HAS_CAPTURE", seems clean enough.

I'll try with that as soon as possible. Otherwise, if you're able to try it on all your non-Linux configurations and verify that it works and that you like it, feel free to send a PR.

Thanks

**Comment by evgeni** [comment]
@gianlucaborello :+1: good idea. works fine on kFreeBSD and Linux for me now.
