### ISSUE TITLE
Obtaining the full exe path

### ISSUE THREAD

**Issue by vrastogi** [draios/sysdig#717]
Sysdig logs currently do not provide the full exe path. In some cases, proc.exe is helpful but it does not always work. Can we get the full path, which is the same as provided `/proc/{pid}/exe`?

I would be happy to contribute a patch if someone can suggest where in the code to look at.

**Comment by gianlucaborello** [comment]
Please refer to this thread: https://groups.google.com/forum/#!topic/sysdig/5xqROcQ7C78

**Comment by vrastogi** [comment]
Great, I will try the patch myself, but will it be possible to include it in the official release as well? It greatly simplifies matters when the upstream itself has those features.

**Comment by gianlucaborello** [comment]
If you're able to revamp the patch and test it thoroughly, certainly submit a PR and we can start the review process and see where it leads.

**Comment by vrastogi** [comment]
Thank you, I will do so.

**Comment by arossert** [comment]
Will this support older kernels (2.6.18)?

**Comment by vrastogi** [comment]
Hi, can you please look at PR#730?

**Comment by arossert** [comment]
@vrastogi, do you know what changes needed to be made in order for this change to compile on older kernels (2.6.18)?

I tried and this is the error that i got:
`error: ‘struct mm_struct’ has no member named ‘exe_file’`

**Comment by vrastogi** [comment]
@arossert I have not tested on that old kernels. It should work on 2.6.32 and newer though.

It looks like the data structures have changed significantly between very old kernels and newer ones. I will try to look into this. Do you have any ideas where to look?

**Comment by arossert** [comment]
@vrastogi I do not have a lot of experience with kernel programming so currently no.
I will try to find something as well and if something will come up i will update you.

I'm using sysding on RHEL5.4, this is why i need support in older kernels.

Thanks.

**Comment by vrastogi** [comment]
I am looking into this. If it works I will push it soon.

**Comment by arossert** [comment]
@vrastogi is there anything new regarding this change?

**Comment by vrastogi** [comment]
@arossert I have my changes ready but apparently, vanilla sysdig also does not build on 2.6.18. The error that shows the offending location on sysdig dev head:
```
/root/sysdig/driver/ppm_events.c: In function ‘compute_snaplen’:
/root/sysdig/driver/ppm_events.c:212: error: ‘struct file’ has no member named ‘f_path’
```
Can you please confirm if you are facing this issue as well?

**Comment by arossert** [comment]
Yes, there are some changed that you need to apply to compile on kernel 2.6.18, sorry that I didn't mention that before.
You can look at my pull request #695, it has already approved.

If you don't want to include this changes in your pull request, can you share the changes with me and I will include them in my pull?

**Comment by vrastogi** [comment]
@arossert, your PR has not been merged yet. So, I applied your commit to the top of current sysdig dev head. This allows compilation but at runtime (`sysdig -w trace.scap`) results in the following assertion failure.

> sysdig: /root/vanilla/sysdig-dev/userspace/libscap/scap_procs.c:382: scap_get_vtid: Assertion `0' failed.
> Aborted

Do you not see this? I tested this on Centos 5.11 with kernel 2.6.18.

**Comment by arossert** [comment]
I didn't see this before, Is the same happening without the -w flag (output to screen)?

I made the fix on 0.13.0 version, I will try to check it on the dev branch

**Comment by vrastogi** [comment]
@arossert yes, the same happens without the -w flag.

**Comment by arossert** [comment]
@vrastogi I have just compiled the DEV branch and it seems that it is working fine.

I'm on RHEL5 kernel 2.6.18-409, I know that tracepoints only backported to kernel 2.6.18-331 and above, what is the kernel release version in your machine?

**Comment by vrastogi** [comment]
@arossert I am on 2.6.18-418.el5

**Comment by arossert** [comment]
@vrastogi thanks for the commit, I will try to compile and run and will report back

**Comment by arossert** [comment]
@vrastogi I successfully compiled your code with my changes on RHEL5 2.6.18-417.el5.
when I run sysdig with the new module it makes my VM crash.

This is what I did:
```./sysdig proc.name = python```

And on a different terminal, I just opened python.
This is what I get:
<img width="423" alt="screen shot 2017-02-26 at 18 40 09" src="https://cloud.githubusercontent.com/assets/7085494/23341621/ab41bf34-fc53-11e6-8f67-4ca1883cb41d.png">

**Comment by vrastogi** [comment]
@arossert yes, bugs are possible. I could not test my changes on 2.6.18
because even sysdig with just your changes was not working.

Is it possible for you to compile and run sysdig on Centos 5.11 with latest
kernel updates? It will help identify where the problem is.

Thanks,
Vaibhav

**Comment by arossert** [comment]
@vrastogi I will try to set up a Centos 5.11 machine and compile the code

**Comment by arossert** [comment]
@vrastogi I just installed Centos5.11 with all updates (kernel 2.6.18-419.el5).
I took the latest sysdig version (0.15.0) with my RHEL5 patch and it compiled and executed without any issues.

**Comment by arossert** [comment]
@vrastogi is there anything new with this?
Can I do something to help?

**Comment by vrastogi** [comment]
@arossert I have not made much progress yet with this, will let you know
when I have some results.

**Comment by JohannesTK** [comment]
That's a highly needed feature, looking forward to it!

**Comment by vrastogi** [comment]
@arossert, @JohannesTK You may find the discussion on PR #730 interesting.

**Comment by arossert** [comment]
Why don't sysdig taking this value from /proc while parsing the process details?
I just examined `scap_procs.c` and in `scap_proc_add_from_proc()` (line 477) I can see this code:
```	//
	// Gather the executable full name
	//
	target_res = readlink(filename, target_name, sizeof(target_name) - 1);			// Getting the target of the exe, i.e. to which binary it points to
```
But the `target_name` value is never used, is there a special reason for that?

**Comment by luca3m** [comment]
`/proc` is parsed only at the beginning, afterwards processes are added in memory directly from sysdig events

**Comment by arossert** [comment]
I believe that this cab be closed now since #934 was merged
