### ISSUE TITLE
Failing to compile with DKMS on Ubuntu 10.04 with missing asm/asm-offsets.h

### ISSUE THREAD

**Issue by andyshinn** [draios/sysdig#333]
I am trying to compile on Ubuntu 10.04 running as a EC2 instance. DKMS is failing with the following error:

```
polleverywhere@ip-10-0-0-145:~$ cat /var/lib/dkms/sysdig/0.1.98/build/make.log
DKMS make.log for sysdig-0.1.98 for kernel 2.6.32-342-ec2 (x86_64)
Wed Mar  4 01:18:27 UTC 2015
make: Entering directory `/usr/src/linux-headers-2.6.32-342-ec2'
  Updating /var/lib/dkms/sysdig/0.1.98/build/Makefile.xen
  LD      /var/lib/dkms/sysdig/0.1.98/build/built-in.o
  CC [M]  /var/lib/dkms/sysdig/0.1.98/build/main.o
In file included from /usr/src/linux-headers-2.6.32-342-ec2/arch/x86/include/asm/unistd.h:5,
                 from include/linux/unistd.h:7,
                 from /usr/src/linux-headers-2.6.32-342-ec2/arch/x86/include/asm/seccomp_64.h:4,
                 from /usr/src/linux-headers-2.6.32-342-ec2/arch/x86/include/asm/seccomp.h:4,
                 from include/linux/seccomp.h:8,
                 from include/linux/sched.h:80,
                 from /var/lib/dkms/sysdig/0.1.98/build/main.c:33:
/usr/src/linux-headers-2.6.32-342-ec2/arch/x86/include/asm/unistd_64.h:693:29: error: asm/asm-offsets.h: No such file or directory
/var/lib/dkms/sysdig/0.1.98/build/main.c: In function ‘ppm_ioctl’:
/var/lib/dkms/sysdig/0.1.98/build/main.c:465: error: ‘__NR_syscall_max’ undeclared (first use in this function)
/var/lib/dkms/sysdig/0.1.98/build/main.c:465: error: (Each undeclared identifier is reported only once
/var/lib/dkms/sysdig/0.1.98/build/main.c:465: error: for each function it appears in.)
make[1]: *** [/var/lib/dkms/sysdig/0.1.98/build/main.o] Error 1
make: *** [_module_/var/lib/dkms/sysdig/0.1.98/build] Error 2
make: Leaving directory `/usr/src/linux-headers-2.6.32-342-ec2'
```

I am trying to install via the Sysdig Cloud agent. But this particular part seems to be specific to the Sysdig kernel module. I have confirmed that the correct Linux headers are available from the `linux-headers-2.6.32-342-ec2` package.

The one thing I do notice is that  asm-offsets.h is on the system but in a different directory at `asm-x86/asm-offsets.h` instead of `asm/asm-offsets.h`. Is this possibly a bug in the detection of the `asm-offsets.h` location?

**Comment by gianlucaborello** [comment]
Hi,

Unfortunately the EC2 kernel on Ubuntu 10.04 has a missing symlink in the headers directory, making it impossible to compile certain modules. The issue never got fixed upstream and now 10.04 reached end of life.
This should fix:

```
sudo ln -nsf /usr/src/linux-headers-`uname -r`/include/asm-x86 /usr/src/linux-headers-`uname -r`/include/asm
sudo apt-get -y install
```

Thanks

**Comment by andyshinn** [comment]
Makes sense. Didn't realize it was an upstream issue. I just happen to have some older Ubuntu machines to test with. Hopefully, won't need to deploy it anymore on 10.04. I made a note of this on https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-for-Linux. Let me know if that might be better places in a *Troubleshooting* section at the end of the document.

**Comment by gianlucaborello** [comment]
Thanks for the note in the wiki. I might prefer a Troubleshooting section at the end of the document to avoid further clutter in the installation instructions, considering that people using Ubuntu 10.04 at this point are the 0.01% :)

**Comment by andyshinn** [comment]
True. Updated.
