### ISSUE TITLE
DKMS Module Build Failure on Arch Linux

### ISSUE THREAD

**Issue by tianze0926** [draios/sysdig#1977]
When I try to install `sysdig` on Arch by running `sudo pacman -S sysdig-dkms`, the following error occurred:

```
...
(10/10) installing sysdig-dkms                                                      [################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod scap/3.0.1+driver -k 6.2.8-arch1-1
Error! Bad return status for module build on kernel: 6.2.8-arch1-1 (x86_64)
Consult /var/lib/dkms/scap/3.0.1+driver/build/make.log for more information.
==> WARNING: `dkms install --no-depmod scap/3.0.1+driver -k 6.2.8-arch1-1' exited 10
```

`/var/lib/dkms/scap/3.0.1+driver/build/make.log`:

```
DKMS make.log for scap-3.0.1+driver for kernel 6.2.8-arch1-1 (x86_64)
Fri Mar 24 07:43:53 PM CST 2023
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/main.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/dynamic_params_table.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/fillers_table.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/flags_table.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/ppm_events.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/ppm_fillers.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/event_table.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/syscall_table.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/ppm_cputime.o
  CC [M]  /var/lib/dkms/scap/3.0.1+driver/build/tp_table.o
/var/lib/dkms/scap/3.0.1+driver/build/main.c: In function ‘scap_init’:
/var/lib/dkms/scap/3.0.1+driver/build/main.c:2788:30: error: assignment to ‘char * (*)(const struct device *, umode_t *)’ {aka ‘char * (*)(const struct device *, short unsigned int *)’} from incompatible pointer type ‘char * (*)(struct device *, umode_t *)’ {aka ‘char * (*)(struct device *, short unsigned int *)’} [-Werror=incompatible-pointer-types]
 2788 |         g_ppm_class->devnode = ppm_devnode;
      |                              ^
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:252: /var/lib/dkms/scap/3.0.1+driver/build/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:2021: /var/lib/dkms/scap/3.0.1+driver/build] Error 2
```

**Comment by therealbobo** [comment]
This issue is related to the 6.2 kernel and was fixed with the 4.0.1 driver. In the next days we'll do a release to bump the driver! 😄 @tianze0926
