### ISSUE TITLE
manual installation  with err: Error! Bad return status for module build on kernel: 5.4.171-1.el7.elrepo.x86_64 (x86_64)

### ISSUE THREAD

**Issue by jiaxingli** [draios/sysdig#1826]
system: centos7
kernel: 
kernel-lt-5.4.171-1.el7.elrepo.x86_64
kernel-lt-tools-libs-5.4.171-1.el7.elrepo.x86_64
kernel-lt-devel-5.4.171-1.el7.elrepo.x86_64
kernel-lt-tools-5.4.171-1.el7.elrepo.x86_64
kernel-lt-headers-5.4.171-1.el7.elrepo.x86_64
kernel-lt-tools-libs-devel-5.4.171-1.el7.elrepo.x86_64

dkms:
dkms-3.0.3-1.el7.noarch.rpm

sysdig: sysdig-0.28.0-x86_64.rpm

rpm install sysdig  report below:
cleaning build area...
make -j2 KERNELRELEASE=5.4.171-1.el7.elrepo.x86_64 -C /lib/modules/5.4.171-1.el7.elrepo.x86_64/build M=/var/lib/dkms/scap/2160111cd088aea9ae2235d3385ecb0b1ab6623c/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.171-1.el7.elrepo.x86_64 (x86_64)
Consult /var/lib/dkms/scap/2160111cd088aea9ae2235d3385ecb0b1ab6623c/build/make.log for more information.

 /var/lib/dkms/scap/2160111cd088aea9ae2235d3385ecb0b1ab6623c/build/make.log with below:
      ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:214:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1759:6: note: in expansion of macro ‘WARN_ON_ONCE’
  if (WARN_ON_ONCE((unsigned short)tx_queue >= USHRT_MAX))
      ^
./include/net/sock.h: In function ‘sk_rx_queue_set’:
././include/linux/compiler_types.h:214:24: error: expected ‘(’ before ‘__inline’
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1785:7: note: in expansion of macro ‘WARN_ON_ONCE’
   if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
       ^
In file included from ./include/linux/bug.h:5:0,
                 from ./arch/x86/include/asm/paravirt.h:15,
                 from ./arch/x86/include/asm/irqflags.h:72,
                 from ./include/linux/irqflags.h:16,
                 from ./include/linux/rcupdate.h:26,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./arch/x86/include/asm/syscall.h:14,
                 from /var/lib/dkms/scap/2160111cd088aea9ae2235d3385ecb0b1ab6623c/build/main.c:19:
./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1785:7: note: in expansion of macro ‘WARN_ON_ONCE’
   if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
       ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:214:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1785:7: note: in expansion of macro ‘WARN_ON_ONCE’
   if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
       ^
./include/net/sock.h: In function ‘sock_graft’:
././include/linux/compiler_types.h:214:24: error: expected ‘(’ before ‘__inline’
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
   __WARN();      \
   ^
./include/net/sock.h:1838:2: note: in expansion of macro ‘WARN_ON’
  WARN_ON(parent->sk);
  ^
In file included from ./include/linux/bug.h:5:0,
                 from ./arch/x86/include/asm/paravirt.h:15,
                 from ./arch/x86/include/asm/irqflags.h:72,
                 from ./include/linux/irqflags.h:16,
                 from ./include/linux/rcupdate.h:26,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./arch/x86/include/asm/syscall.h:14,
                 from /var/lib/dkms/scap/2160111cd088aea9ae2235d3385ecb0b1ab6623c/build/main.c:19:
./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
   __WARN();      \
   ^
./include/net/sock.h:1838:2: note: in expansion of macro ‘WARN_ON’
  WARN_ON(parent->sk);
  ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:214:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
   __WARN();      \
   ^
./include/net/sock.h:1838:2: note: in expansion of macro ‘WARN_ON’
  WARN_ON(parent->sk);
  ^
./include/net/request_sock.h: In function ‘reqsk_free’:
././include/linux/compiler_types.h:214:24: error: expected ‘(’ before ‘__inline’
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/request_sock.h:119:2: note: in expansion of macro ‘WARN_ON_ONCE’
  WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
  ^
In file included from ./include/linux/bug.h:5:0,
                 from ./arch/x86/include/asm/paravirt.h:15,
                 from ./arch/x86/include/asm/irqflags.h:72,
                 from ./include/linux/irqflags.h:16,
                 from ./include/linux/rcupdate.h:26,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./arch/x86/include/asm/syscall.h:14,
                 from /var/lib/dkms/scap/2160111cd088aea9ae2235d3385ecb0b1ab6623c/build/main.c:19:
./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/request_sock.h:119:2: note: in expansion of macro ‘WARN_ON_ONCE’
  WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
  ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:214:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/request_sock.h:119:2: note: in expansion of macro ‘WARN_ON_ONCE’
  WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
  ^
make[2]: *** [/var/lib/dkms/scap/2160111cd088aea9ae2235d3385ecb0b1ab6623c/build/main.o] Error 1
make[1]: *** [/var/lib/dkms/scap/2160111cd088aea9ae2235d3385ecb0b1ab6623c/build] Error 2
make: *** [sub-make] Error 2
make: Leaving directory `/usr/src/kernels/5.4.171-1.el7.elrepo.x86_64'
