### ISSUE TITLE
Installation fail on Centos 6 based distro (CloudLinux)

### ISSUE THREAD

**Issue by do11** [draios/sysdig#568]
There is Centos based distro called CloudLinux. Installation fail:
```
root@cl:~# yum install sysdig
Loaded plugins: changelog, fastestmirror, rhnplugin
Setting up Install Process
Loading mirror speeds from cached hostfile
 * cloudlinux-x86_64-server-6: cl-mirror.cloud.dk
 * epel: mirror.awanti.com
Resolving Dependencies
--> Running transaction check
---> Package sysdig.x86_64 0:0.8.0-1 will be installed
--> Processing Dependency: dkms for package: sysdig-0.8.0-1.x86_64
--> Running transaction check
---> Package dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================================================
 Package                           Arch                              Version                                                Repository                         Size
====================================================================================================================================================================
Installing:
 sysdig                            x86_64                            0.8.0-1                                                draios                            3.6 M
Installing for dependencies:
 dkms                              noarch                            2.2.0.3-30.git.7c3e7c5.el6                             epel                               77 k

Transaction Summary
====================================================================================================================================================================
Install       2 Package(s)

Total download size: 3.7 M
Installed size: 11 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): dkms-2.2.0.3-30.git.7c3e7c5.el6.noarch.rpm                                                                                            |  77 kB     00:00
(2/2): sysdig-0.8.0-x86_64.rpm                                                                                                               | 3.6 MB     00:05
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                               576 kB/s | 3.7 MB     00:06
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : dkms-2.2.0.3-30.git.7c3e7c5.el6.noarch                                                                                                           1/2
  Installing : sysdig-0.8.0-1.x86_64                                                                                                                            2/2

Creating symlink /var/lib/dkms/sysdig/0.8.0/source ->
                 /usr/src/sysdig-0.8.0

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make KERNELRELEASE=2.6.32-673.8.1.lve1.4.3.el6.x86_64 -C /lib/modules/2.6.32-673.8.1.lve1.4.3.el6.x86_64/build M=/var/lib/dkms/sysdig/0.8.0/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 2.6.32-673.8.1.lve1.4.3.el6.x86_64 (x86_64)
Consult /var/lib/dkms/sysdig/0.8.0/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make KERNELRELEASE=2.6.32-673.8.1.lve1.4.3.el6.x86_64 -C /lib/modules/2.6.32-673.8.1.lve1.4.3.el6.x86_64/build M=/var/lib/dkms/sysdig/0.8.0/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 2.6.32-673.8.1.lve1.4.3.el6.x86_64 (x86_64)
Consult /var/lib/dkms/sysdig/0.8.0/build/make.log for more information.
warning: %post(sysdig-0.8.0-1.x86_64) scriptlet failed, exit status 10
Non-fatal POSTIN scriptlet failure in rpm package sysdig-0.8.0-1.x86_64
  Verifying  : dkms-2.2.0.3-30.git.7c3e7c5.el6.noarch                                                                                                           1/2
  Verifying  : sysdig-0.8.0-1.x86_64                                                                                                                            2/2

Installed:
  sysdig.x86_64 0:0.8.0-1

Dependency Installed:
  dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el6

Complete!

root@cl:~# cat /var/lib/dkms/sysdig/0.8.0/build/make.log
DKMS make.log for sysdig-0.8.0 for kernel 2.6.32-673.8.1.lve1.4.3.el6.x86_64 (x86_64)
Tue Mar 29 21:26:26 MSK 2016
make: Entering directory `/usr/src/kernels/2.6.32-673.8.1.lve1.4.3.el6.x86_64'
  LD      /var/lib/dkms/sysdig/0.8.0/build/built-in.o
  CC [M]  /var/lib/dkms/sysdig/0.8.0/build/main.o
/var/lib/dkms/sysdig/0.8.0/build/main.c: In function Б─≤ppm_ioctlБ─≥:
/var/lib/dkms/sysdig/0.8.0/build/main.c:623: error: implicit declaration of function Б─≤for_each_processБ─≥
/var/lib/dkms/sysdig/0.8.0/build/main.c:623: error: expected Б─≤;Б─≥ before Б─≤{Б─≥ token
/var/lib/dkms/sysdig/0.8.0/build/main.c:597: warning: unused variable Б─≤tБ─≥
make[1]: *** [/var/lib/dkms/sysdig/0.8.0/build/main.o] Error 1
make: *** [_module_/var/lib/dkms/sysdig/0.8.0/build] Error 2
make: Leaving directory `/usr/src/kernels/2.6.32-673.8.1.lve1.4.3.el6.x86_64'

root@cl:~# yum -y install kernel-devel-$(uname -r)
Loaded plugins: changelog, fastestmirror, rhnplugin
Setting up Install Process
Loading mirror speeds from cached hostfile
 * cloudlinux-x86_64-server-6: cl-mirror.cloud.dk
 * epel: mirror.awanti.com
Package kernel-devel-2.6.32-673.8.1.lve1.4.3.el6.x86_64 already installed and latest version
Nothing to do

```
